USE MASTER;
GO
sp_configure 'show advanced options', 1
GO
RECONFIGURE;
GO
sp_configure 'contained database authentication', 1
GO
RECONFIGURE;
GO
sp_configure 'show advanced options', 0 
GO
RECONFIGURE;
GO
CREATE DATABASE MEMOIRS_DB
CONTAINMENT = PARTIAL
ON
	(NAME = MEMOIRS_DAT,
	FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\MEMOIRS_DAT.mdf',
	SIZE = 64MB,
	FILEGROWTH = 4MB)
LOG ON
	(NAME = MEMOIRS_LOG,
	FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\MEMOIRS_DAT.ldf',
	SIZE = 16MB,
	FILEGROWTH = 4MB)
COLLATE Cyrillic_General_CS_AS
WITH DEFAULT_LANGUAGE = Russian, DEFAULT_FULLTEXT_LANGUAGE = Russian;
GO


USE MASTER;
GO
EXEC xp_instance_regwrite N'HKEY_LOCAL_MACHINE', N'Software\Microsoft\MSSQLServer\MSSQLServer', N'LoginMode', REG_DWORD, 2;
GO
CREATE LOGIN PrivateNotes WITH PASSWORD = 'PrivateNotes';
USE MEMOIRS_DB;
GO
CREATE USER PrivateNotes FOR LOGIN PrivateNotes;
GO
EXEC sp_addrolemember N'db_owner', N'PrivateNotes';
GO


USE MEMOIRS_DB;
GO
CREATE TABLE MEMOIRS
(
	MEMOIR_ID BIGINT IDENTITY PRIMARY KEY,
	USER_GUID UNIQUEIDENTIFIER FOREIGN KEY
		REFERENCES USERS(USER_GUID) NOT NULL,
	MEMOIR_TEXT TEXT NOT NULL,
	MEMOIR_TITLE TEXT DEFAULT 'Без темы...' NOT NULL,
	MEMOIR_DATE_RECORD DATETIME NOT NULL,
	MEMOIR_DATE_CHANGE DATETIME DEFAULT GETDATE() NOT NULL
);
GO
CREATE TABLE USERS
(
	USER_GUID UNIQUEIDENTIFIER DEFAULT NEWSEQUENTIALID() PRIMARY KEY,
	USER_LOGIN NVARCHAR(50) NOT NULL UNIQUE,
	USER_HASH CHAR(64) NOT NULL,
	REGISTRATION_DATE DATETIME DEFAULT GETDATE() NOT NULL
);
GO