//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrivateMemoirs
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities(string str)
            : base(str)
        {
            Database.Connection.ConnectionString = str;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Entity<USERS>().HasKey(u => new { u.USER_GUID });
            modelBuilder.Entity<MEMOIRS>().HasKey(m => new { m.MEMOIR_ID });
        }

        public virtual DbSet<MEMOIRS> MEMOIRS { get; set; }
        public virtual DbSet<USERS> USERS { get; set; }
    }
}